# plot_ensemble_figure.R
# -----------------------------------------------------------------------
# Three-panel ensemble figure summarizing chronological uncertainty in
# peak detection for a single charcoal record.
#
# RATIONALE
# ---------
# Standard CharAnalysis runs use a single "best-estimate" age-depth model
# (typically the median of a Bayesian age model such as Bacon). This
# ignores age uncertainty: the same sediment sample may be assigned
# meaningfully different ages across the posterior ensemble of chronologies,
# which affects both (1) the accumulation-rate denominators used to compute
# CHAR and (2) the absolute dates assigned to detected peaks. The ensemble
# approach reruns the full pipeline once per chronology in an N-member
# ensemble (default N = 1000, generated by Bacon or MC_AgeDepth.m) and
# summarises two quantities per reference peak:
#
#   Detection frequency -- fraction of ensemble iterations (%) that identify
#                   a fire event near the same time as the reference run.
#                   Reflects how robustly the peak survives across plausible
#                   chronologies; values < ~70% suggest the event may be
#                   an artifact of the single best-estimate chronology.
#
#   Timing CI    -- 95% confidence interval on the detected age of each
#                   reference peak across the ensemble. Reflects how much
#                   chronological uncertainty translates into uncertainty
#                   in the absolute timing of a fire event.
#
# PANEL DESCRIPTIONS AND METHODS
# --------------------------------
# Panel (a) — CHAR time series
#   Replicates char_plot_sni() panel (a): interpolated charcoal
#   accumulation rate (CHAR), background curve, and positive/negative
#   thresholds from the reference (single-chronology) run. Peak
#   identifications from the reference run are shown as crosses.
#
# Panel (b) — Signal-to-noise index (SNI)
#   SNI time series from the reference run; dashed line at SNI = 3.0
#   (Kelly et al. 2011 threshold for reliable peak detection).
#
# Panel (c) — Detection frequency and timing uncertainty (combined)
#   One point + horizontal bar per reference peak.
#   x = cal yr BP (same axis as panels a and b)
#   y = detection frequency (% of ensemble iterations identifying this peak)
#   horizontal bar = 95% CI on detected peak age across all iterations
#   dot = reference peak age from the single best-estimate chronology run
#
#   The y-axis lower limit is data-adaptive: floored to the nearest 25%
#   below the minimum observed detection frequency. This preserves visual
#   resolution for the observed range while keeping the axis honest.
#   Override with y_floor (line marked below) for cross-record comparisons
#   (e.g., set y_floor <- 0 for a 0-100% scale).
#
#   Matching algorithm (run_ensemble_analysis.R):
#     For each reference peak k (k = 1 … n_peaks) and each ensemble
#     iteration i (i = 1 … N):
#       1. Find all time steps with peaks_matrix[t, i] == 1.
#       2. Identify the single closest detected age to the reference
#          peak age.
#       3. If that distance ≤ half-window, assign the detected age to
#          peak k for iteration i.
#     The half-window = max(mean_mFRI / 2, yrInterp), where mean_mFRI
#     is the Weibull mean fire-return interval averaged across zones
#     (from out$post$FRI_params_zone[, 2]).  The reference-peak-first
#     loop guarantees at most one detection per reference peak per
#     iteration, so detection frequency ≤ 100%.
#
# FUTURE WORK
# -----------
# Package char_run_ensemble() as an exported function with Roxygen docs.
# Replace MC_AgeDepth.m chronology generation with an rbacon interface.
# Write a dedicated vignette (vignettes/chronological_uncertainty.Rmd)
# covering rationale, algorithm details, and worked CH10 example.
#
# Requires in workspace: out, peak_summaries
#
# peak_summaries can be loaded from the saved CSV (fast path, no re-analysis):
#   peak_summaries <- read.csv("CharAnalysis_2_0_R/tests/CH10_peakAgeUncertainty.csv")
# The CSV contains n_iter so the figure title is self-contained.
#
# out must come from a reference CharAnalysis run (panels a and b):
#   devtools::load_all("CharAnalysis_2_0_R")
#   out <- CharAnalysis("CharAnalysis_2_0_R/inst/validation/CH10_charParams.csv",
#                       plots = FALSE)
#
# If neither object is present, run_ensemble_analysis.R is sourced automatically.
#
# Run:
#   setwd("C:/Users/philip.higuera/OneDrive - The University of Montana/1_phiguera/1_working/CharAnalysis")
#   source("CharAnalysis_2_0_R/tests/plot_ensemble_figure.R")
# -----------------------------------------------------------------------

library(CharAnalysis)
library(ggplot2)
library(patchwork)

setwd("C:/Users/philip.higuera/OneDrive - The University of Montana/1_phiguera/1_working/CharAnalysis")

# Save figure as PDF? 1 = yes, 0 = no (default).
# When sourced from char_run_ensemble.R, save_pdf is set there and
# this line is skipped. Only applies when run standalone.
if (!exists("save_pdf")) save_pdf <- 0

# ---- Load data if not already in workspace ----------------------------
if (!exists("out") || !exists("peak_summaries")) {
  message("Running ensemble analysis pipeline...")
  source("CharAnalysis_2_0_R/tests/run_ensemble_analysis.R")
} else {
  message("Using existing 'out' and 'peak_summaries' from workspace.")
}

# ---- Normalize peak_summaries column names ----------------------------
# If peak_summaries was loaded from the CSV (charResults-style names),
# rename to R-friendly names used throughout this script.
csv_to_r <- c(
  "age Top_i (yr BP)"       = "ref_age",
  "n ensemble (iterations)" = "n_iter",
  "detection freq (%)"      = "prob",
  "n detected (peaks)"      = "n_detected",
  "mean age (yr BP)"        = "mean_age",
  "median age (yr BP)"      = "median_age",
  "sd age (yr)"             = "sd_age",
  "CI80 lo (yr BP)"         = "ci80_lo",
  "CI80 hi (yr BP)"         = "ci80_hi",
  "CI95 lo (yr BP)"         = "ci95_lo",
  "CI95 hi (yr BP)"         = "ci95_hi"
)
needs_rename <- intersect(names(csv_to_r), names(peak_summaries))
if (length(needs_rename) > 0L) {
  names(peak_summaries)[match(needs_rename, names(peak_summaries))] <-
    csv_to_r[needs_rename]
  # prob column in CSV is already %; convert back to 0-1 for internal use
  if ("prob" %in% names(peak_summaries) && max(peak_summaries$prob, na.rm = TRUE) > 1)
    peak_summaries$prob <- peak_summaries$prob / 100
  message("peak_summaries: CSV column names normalised to R-friendly names.")
}

# ---- Common axis parameters (match existing CharAnalysis figures) -----
charcoal     <- out$charcoal
char_thresh  <- out$char_thresh
peak_analysis <- out$peak_analysis
pretreatment <- out$pretreatment
post         <- out$post
site         <- out$site

zone_div    <- pretreatment$zoneDiv
x_ticks     <- seq(0, max(zone_div, na.rm = TRUE), by = 1000)
x_minor     <- seq(0, max(zone_div, na.rm = TRUE), by = 500)
x_lims      <- c(max(zone_div, na.rm = TRUE), min(zone_div, na.rm = TRUE))
transform   <- pretreatment$transform
cPeak       <- peak_analysis$cPeak

has_ggtext  <- requireNamespace("ggtext", quietly = TRUE)
y_lbl_axis  <- if (has_ggtext) ggtext::element_markdown() else element_text()
y_lbl <- if (has_ggtext) {
  switch(as.character(transform),
    "1" = "log CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)",
    "2" = "ln CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)",
         "CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)")
} else "CHAR (# cm^-2 yr^-1)"

# ---- Panel (a): CHAR + background + peaks ----------------------------
x  <- charcoal$ybpI
y  <- charcoal$accI
y2 <- charcoal$accIS
y3 <- char_thresh$pos[, ncol(char_thresh$pos)]
y4 <- if (is.matrix(char_thresh$neg)) char_thresh$neg[, 1L] else
      rep(char_thresh$neg[1L], length(x))

t_pos_line <- if (cPeak == 1L) y2 + y3 else y2 * y3
t_neg_line <- if (cPeak == 1L) y2 + y4 else y2 * y4

ccp      <- post$CharcoalCharPeaks
T_thresh <- ncol(ccp)
y_max    <- max(y, na.rm = TRUE)

lev <- c(0.78, 0.85, 0.92)
if (T_thresh < 3L) lev <- lev[(4L - T_thresh):3L]
sel_col <- T_thresh
tv      <- peak_analysis$threshValues

non_sel_idx <- setdiff(seq_len(T_thresh), sel_col)
non_sel_tv  <- tv[non_sel_idx]
show_cols   <- utils::head(non_sel_idx[order(non_sel_tv)], 3L)

df_bar  <- data.frame(x = x, y = y)
df_back <- data.frame(x = x, y2 = y2)
df_tpos <- data.frame(x = x, t = t_pos_line)
df_tneg <- data.frame(x = x, t = t_neg_line)

pa <- ggplot(df_bar, aes(x = x, y = y)) +
  geom_col(fill = "black", colour = "black",
           width = mean(diff(x), na.rm = TRUE)) +
  geom_line(data = df_back, aes(x = x, y = y2),
            colour = "grey50", linewidth = 1.2) +
  geom_line(data = df_tpos, aes(x = x, y = t),
            colour = "red", linewidth = 0.6) +
  geom_line(data = df_tneg, aes(x = x, y = t),
            colour = "red", linewidth = 0.6)

# Zone dividers
if (length(zone_div) > 2L) {
  for (zd in zone_div[-c(1L, length(zone_div))]) {
    pa <- pa + annotate("segment",
      x = zd, xend = zd,
      y = y_max * 1.01, yend = y_max * 1.10,
      colour = "grey50", linewidth = 1.0)
  }
  for (z in seq_along(zone_div[-1L])) {
    mid_x <- mean(zone_div[z:(z + 1L)])
    pa <- pa + annotate("text", x = mid_x, y = y_max * 1.055,
      label = paste0("Zone ", z), hjust = 0.5, size = 2.5)
  }
}

# Non-selected threshold peak markers
for (rank in seq_along(show_cols)) {
  j      <- show_cols[rank]
  lev_j  <- lev[rank]
  pk_idx <- which(ccp[, j] > 0)
  if (length(pk_idx) > 0L) {
    df_pk <- data.frame(x = x[pk_idx], y = y_max * lev_j)
    pa <- pa + geom_point(data = df_pk, aes(x = x, y = y),
      shape = 16L, size = 1, colour = "grey50")
  }
}

# Selected threshold peak markers
pk_idx_sel <- which(ccp[, sel_col] > 0)
if (length(pk_idx_sel) > 0L) {
  sorted_tv  <- non_sel_tv[order(non_sel_tv)][seq_along(show_cols)]
  match_rank <- which(sorted_tv == tv[sel_col])
  if (length(match_rank) == 0L) match_rank <- ceiling(length(show_cols) / 2L)
  mIndex <- lev[match_rank[1L]]
  df_pk_sel <- data.frame(x = x[pk_idx_sel], y = y_max * mIndex)
  pa <- pa +
    geom_point(data = df_pk_sel, aes(x = x, y = y),
      shape = 3L, size = 2.5, colour = "white", stroke = 1.5) +
    geom_point(data = df_pk_sel, aes(x = x, y = y),
      shape = 3L, size = 2.5, colour = "black", stroke = 0.9)
}

pa <- pa +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = c(0, y_max * 1.15), expand = expansion(0)) +
  theme_classic() +
  theme(axis.title.y = y_lbl_axis,
        axis.title.x = element_blank(),
        axis.text.x  = element_blank()) +
  labs(title = paste0(site,
    " (a) C_interpolated, C_background, and peak ID (+)"), y = y_lbl)
if (has_ggtext) pa <- pa + theme(plot.title = ggtext::element_markdown())


# ---- Panel (b): SNI --------------------------------------------------
sni_val    <- char_thresh$SNI
sni_series <- if (length(sni_val) == 1L) rep(sni_val, length(x)) else sni_val
df_sni     <- data.frame(x = x, sni = sni_series)
y_tick_sni <- pretty(c(0, max(sni_series, na.rm = TRUE)), n = 4)
y_lim_sni  <- c(0, max(y_tick_sni))

p_sni <- ggplot(df_sni, aes(x = x, y = sni)) +
  geom_line(colour = "black", linewidth = 0.7) +
  geom_hline(yintercept = 3, linetype = "dashed") +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = y_lim_sni, breaks = y_tick_sni,
    expand = expansion(0)) +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.text.x  = element_blank()) +
  labs(y = "SNI", title = "(b) Signal-to-noise index")


# ---- Panel (c): Detection frequency vs. timing CI (combined) ---------
# y = detection frequency (% of ensemble iterations); x = cal yr BP
# horizontal bar = 95% CI on detected peak age
# dot = reference peak age from the single best-estimate chronology run
#
# Y-axis lower limit is data-adaptive: floored to the nearest 25% below
# the minimum observed detection frequency. To override for cross-record
# comparisons, set y_floor manually (e.g., y_floor <- 0 or y_floor <- 50).
df_comb   <- peak_summaries
df_comb$det_freq <- df_comb$prob * 100  # convert to percent
n_iter_lbl <- if ("n_iter" %in% names(peak_summaries))
                unique(peak_summaries$n_iter)[1L] else "N"

y_floor <- floor(min(df_comb$det_freq) / 25) * 25  # data-adaptive; override here if needed
y_ceil  <- 105
y_breaks <- seq(y_floor, 100, by = 25)
cap_ht_pct <- (y_ceil - y_floor) * 0.02  # end-cap height scales with y range

p_combined <- ggplot(df_comb, aes(y = det_freq)) +
  geom_errorbarh(aes(xmin = ci95_lo, xmax = ci95_hi),
                 height = cap_ht_pct,
                 colour = "grey30", linewidth = 0.7) +
  geom_point(aes(x = ref_age),
             shape = 16L, size = 2.0, colour = "black") +
  geom_hline(yintercept = 50, linetype = "dashed",
             colour = "grey50", linewidth = 0.5) +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
                  minor_breaks = x_minor, labels = x_ticks / 1000,
                  expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = c(y_floor, y_ceil),
                     breaks = y_breaks,
                     expand = expansion(0)) +
  theme_classic() +
  labs(x = "cal. yr BP (x 1000)",
       y = "Detection frequency (%)",
       title = paste0("(c) Detection frequency and timing uncertainty",
                      "  (95% CI, ", n_iter_lbl, "-chronology ensemble)"))


# ---- Assemble --------------------------------------------------------
fig <- pa / p_sni / p_combined +
  plot_layout(heights = c(3, 1, 1.5))

print(fig)


# ---- Save PDF --------------------------------------------------------
if (save_pdf == 1L) {
  out_pdf <- sprintf("CharAnalysis_2_0_R/tests/%s_ensemble_figure.pdf", site)
  ggsave(out_pdf, plot = fig, width = 7, height = 10, units = "in")
  message(sprintf("Saved: %s", out_pdf))
}
