# plot_ensemble_figure.R
# -----------------------------------------------------------------------
# Four-panel ensemble figure summarizing chronological uncertainty in
# peak detection for a single charcoal record.
#
# RATIONALE
# ---------
# Standard CharAnalysis runs use a single "best-estimate" age-depth model
# (typically the median of a Bayesian age model such as Bacon). This
# ignores age uncertainty: the same sediment sample may be assigned
# meaningfully different ages across the posterior ensemble of chronologies,
# which affects both (1) the accumulation-rate denominators used to compute
# CHAR and (2) the absolute dates assigned to detected peaks. The ensemble
# approach reruns the full pipeline once per chronology in an N-member
# ensemble (default N = 1000, generated by Bacon or MC_AgeDepth.m) and
# summarises two quantities per reference peak:
#
#   P(peak)      -- fraction of ensemble iterations that identify a fire
#                   event near the same time as the reference run. Reflects
#                   how robustly the peak survives across plausible
#                   chronologies; values < ~0.7 suggest the event may be
#                   an artifact of the single best-estimate chronology.
#
#   Timing CI    -- 95% confidence interval on the detected age of each
#                   reference peak across the ensemble. Reflects how much
#                   chronological uncertainty translates into uncertainty
#                   in the absolute timing of a fire event.
#
# PANEL DESCRIPTIONS AND METHODS
# --------------------------------
# Panel (a) — CHAR time series
#   Replicates char_plot_sni() panel (a): interpolated charcoal
#   accumulation rate (CHAR), background curve, and positive/negative
#   thresholds from the reference (single-chronology) run. Peak
#   identifications from the reference run are shown as crosses.
#
# Panel (b) — Signal-to-noise index (SNI)
#   SNI time series from the reference run; dashed line at SNI = 3.0
#   (Kelly et al. 2011 threshold for reliable peak detection).
#
# Panel (c) — P(peak) beeswarm
#   One circle per reference peak; x = reference peak age; circle size
#   scaled to P(peak) using a fixed 5-bin scale (0–20, 21–40, 41–60,
#   61–80, 81–100%) so the encoding is consistent across records.
#
#   Matching algorithm (run_ensemble_analysis.R):
#     For each reference peak k (k = 1 … n_peaks) and each ensemble
#     iteration i (i = 1 … N):
#       1. Find all time steps with peaks_matrix[t, i] == 1.
#       2. Identify the single closest detected age to the reference
#          peak age.
#       3. If that distance ≤ half-window, assign the detected age to
#          peak k for iteration i.
#     The half-window = max(mean_mFRI / 2, yrInterp), where mean_mFRI
#     is the Weibull mean fire-return interval averaged across zones
#     (from out$post$FRI_params_zone[, 2]).  The reference-peak-first
#     loop guarantees at most one detection per reference peak per
#     iteration, so P(peak) = n_detected / N ≤ 1.0.
#
#   Beeswarm jitter: circles are offset in y (cal yr BP units) using a
#   greedy placement algorithm (beeswarm_y()) that prevents overlap
#   based on Euclidean distance in (age, y) space. Bin midpoints (0.10,
#   0.30, …, 0.90) are used as the jitter radius, not raw probabilities,
#   so spacing is consistent across records regardless of the observed
#   probability range.
#
# Panel (d) — 95% CI on peak timing
#   One horizontal bar per reference peak; x-extent = [2.5th, 97.5th
#   percentile] of detected ages across the N ensemble iterations; dot
#   at the reference peak age. For closely spaced peaks, bars are
#   offset in y using bar_y() (x-range overlap + y-proximity check)
#   to prevent overlap.
#
# FUTURE WORK
# -----------
# Package char_run_ensemble() as an exported function with Roxygen docs.
# Replace MC_AgeDepth.m chronology generation with an rbacon interface.
# Write a dedicated vignette (vignettes/chronological_uncertainty.Rmd)
# covering rationale, algorithm details, and worked CH10 example.
#
# Requires in workspace: out, peak_summaries
# If not present, sources run_ensemble_analysis.R automatically.
#
# Run:
#   setwd("C:/Users/philip.higuera/OneDrive - The University of Montana/1_phiguera/1_working/CharAnalysis")
#   source("CharAnalysis_2_0_R/tests/plot_ensemble_figure.R")
# -----------------------------------------------------------------------

library(CharAnalysis)
library(ggplot2)
library(patchwork)

setwd("C:/Users/philip.higuera/OneDrive - The University of Montana/1_phiguera/1_working/CharAnalysis")

# ---- Load data if not already in workspace ----------------------------
if (!exists("out") || !exists("peak_summaries")) {
  message("Running ensemble analysis pipeline...")
  source("CharAnalysis_2_0_R/tests/run_ensemble_analysis.R")
} else {
  message("Using existing 'out' and 'peak_summaries' from workspace.")
}

# ---- Common axis parameters (match existing CharAnalysis figures) -----
charcoal     <- out$charcoal
char_thresh  <- out$char_thresh
peak_analysis <- out$peak_analysis
pretreatment <- out$pretreatment
post         <- out$post
site         <- out$site

zone_div    <- pretreatment$zoneDiv
x_ticks     <- seq(0, max(zone_div, na.rm = TRUE), by = 1000)
x_minor     <- seq(0, max(zone_div, na.rm = TRUE), by = 500)
x_lims      <- c(max(zone_div, na.rm = TRUE), min(zone_div, na.rm = TRUE))
transform   <- pretreatment$transform
cPeak       <- peak_analysis$cPeak

has_ggtext  <- requireNamespace("ggtext", quietly = TRUE)
y_lbl_axis  <- if (has_ggtext) ggtext::element_markdown() else element_text()
y_lbl <- if (has_ggtext) {
  switch(as.character(transform),
    "1" = "log CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)",
    "2" = "ln CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)",
         "CHAR (# cm<sup>-2</sup> yr<sup>-1</sup>)")
} else "CHAR (# cm^-2 yr^-1)"

# ---- Panel (a): CHAR + background + peaks ----------------------------
x  <- charcoal$ybpI
y  <- charcoal$accI
y2 <- charcoal$accIS
y3 <- char_thresh$pos[, ncol(char_thresh$pos)]
y4 <- if (is.matrix(char_thresh$neg)) char_thresh$neg[, 1L] else
      rep(char_thresh$neg[1L], length(x))

t_pos_line <- if (cPeak == 1L) y2 + y3 else y2 * y3
t_neg_line <- if (cPeak == 1L) y2 + y4 else y2 * y4

ccp      <- post$CharcoalCharPeaks
T_thresh <- ncol(ccp)
y_max    <- max(y, na.rm = TRUE)

lev <- c(0.78, 0.85, 0.92)
if (T_thresh < 3L) lev <- lev[(4L - T_thresh):3L]
sel_col <- T_thresh
tv      <- peak_analysis$threshValues

non_sel_idx <- setdiff(seq_len(T_thresh), sel_col)
non_sel_tv  <- tv[non_sel_idx]
show_cols   <- utils::head(non_sel_idx[order(non_sel_tv)], 3L)

df_bar  <- data.frame(x = x, y = y)
df_back <- data.frame(x = x, y2 = y2)
df_tpos <- data.frame(x = x, t = t_pos_line)
df_tneg <- data.frame(x = x, t = t_neg_line)

pa <- ggplot(df_bar, aes(x = x, y = y)) +
  geom_col(fill = "black", colour = "black",
           width = mean(diff(x), na.rm = TRUE)) +
  geom_line(data = df_back, aes(x = x, y = y2),
            colour = "grey50", linewidth = 1.2) +
  geom_line(data = df_tpos, aes(x = x, y = t),
            colour = "red", linewidth = 0.6) +
  geom_line(data = df_tneg, aes(x = x, y = t),
            colour = "red", linewidth = 0.6)

# Zone dividers
if (length(zone_div) > 2L) {
  for (zd in zone_div[-c(1L, length(zone_div))]) {
    pa <- pa + annotate("segment",
      x = zd, xend = zd,
      y = y_max * 1.01, yend = y_max * 1.10,
      colour = "grey50", linewidth = 1.0)
  }
  for (z in seq_along(zone_div[-1L])) {
    mid_x <- mean(zone_div[z:(z + 1L)])
    pa <- pa + annotate("text", x = mid_x, y = y_max * 1.055,
      label = paste0("Zone ", z), hjust = 0.5, size = 2.5)
  }
}

# Non-selected threshold peak markers
for (rank in seq_along(show_cols)) {
  j      <- show_cols[rank]
  lev_j  <- lev[rank]
  pk_idx <- which(ccp[, j] > 0)
  if (length(pk_idx) > 0L) {
    df_pk <- data.frame(x = x[pk_idx], y = y_max * lev_j)
    pa <- pa + geom_point(data = df_pk, aes(x = x, y = y),
      shape = 16L, size = 1, colour = "grey50")
  }
}

# Selected threshold peak markers
pk_idx_sel <- which(ccp[, sel_col] > 0)
if (length(pk_idx_sel) > 0L) {
  sorted_tv  <- non_sel_tv[order(non_sel_tv)][seq_along(show_cols)]
  match_rank <- which(sorted_tv == tv[sel_col])
  if (length(match_rank) == 0L) match_rank <- ceiling(length(show_cols) / 2L)
  mIndex <- lev[match_rank[1L]]
  df_pk_sel <- data.frame(x = x[pk_idx_sel], y = y_max * mIndex)
  pa <- pa +
    geom_point(data = df_pk_sel, aes(x = x, y = y),
      shape = 3L, size = 2.5, colour = "white", stroke = 1.5) +
    geom_point(data = df_pk_sel, aes(x = x, y = y),
      shape = 3L, size = 2.5, colour = "black", stroke = 0.9)
}

pa <- pa +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = c(0, y_max * 1.15), expand = expansion(0)) +
  theme_classic() +
  theme(axis.title.y = y_lbl_axis,
        axis.title.x = element_blank(),
        axis.text.x  = element_blank()) +
  labs(title = paste0(site,
    " (a) C_interpolated, C_background, and peak ID (+)"), y = y_lbl)
if (has_ggtext) pa <- pa + theme(plot.title = ggtext::element_markdown())


# ---- Panel (b): SNI --------------------------------------------------
sni_val    <- char_thresh$SNI
sni_series <- if (length(sni_val) == 1L) rep(sni_val, length(x)) else sni_val
df_sni     <- data.frame(x = x, sni = sni_series)
y_tick_sni <- pretty(c(0, max(sni_series, na.rm = TRUE)), n = 4)
y_lim_sni  <- c(0, max(y_tick_sni))

p_sni <- ggplot(df_sni, aes(x = x, y = sni)) +
  geom_line(colour = "black", linewidth = 0.7) +
  geom_hline(yintercept = 3, linetype = "dashed") +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = y_lim_sni, breaks = y_tick_sni,
    expand = expansion(0)) +
  theme_classic() +
  theme(axis.title.x = element_blank(),
        axis.text.x  = element_blank()) +
  labs(y = "SNI", title = "(b) Signal-to-noise index")


# ---- Jitter functions ------------------------------------------------

# Beeswarm: returns y-offsets in cal yr BP units (same scale as x-axis).
# radius_yr:  radius of a prob = 1 circle in years; tune to match figure size.
# step_yr:    y-step between jitter levels; default = 90% of radius_yr.
beeswarm_y <- function(ages, probs, radius_yr = 180, step_yr = NULL) {
  if (is.null(step_yr)) step_yr <- radius_yr * 0.90
  n   <- length(ages)
  y   <- rep(0, n)
  cx  <- numeric(0); cy_placed <- numeric(0); r_placed <- numeric(0)
  for (i in seq_len(n)) {
    ri   <- radius_yr * probs[i]
    best <- 0L; found <- FALSE
    for (m in 0:12) {
      cands <- if (m == 0L) 0 else c(m * step_yr, -m * step_yr)
      for (cy in cands) {
        ok <- TRUE
        if (length(cx) > 0L) {
          dx  <- ages[i] - cx
          dyi <- cy - cy_placed
          rj  <- r_placed
          if (any(sqrt(dx^2 + dyi^2) < (ri + rj) * 1.05)) ok <- FALSE
        }
        if (ok) { best <- cy; found <- TRUE; break }
      }
      if (found) break
    }
    y[i] <- best
    cx          <- c(cx, ages[i])
    cy_placed   <- c(cy_placed, best)
    r_placed    <- c(r_placed, ri)
  }
  y
}

# Bar jitter: returns y-offsets in cal yr BP units.
# ci_lo / ci_hi:  CI bounds (any units consistent with ages).
# step_yr:        vertical spacing between non-overlapping bar rows.
bar_y <- function(ci_lo, ci_hi, step_yr = 45) {
  n  <- length(ci_lo)
  y  <- rep(0, n)
  xl_p <- numeric(0); xr_p <- numeric(0); cy_p <- numeric(0)
  for (i in seq_len(n)) {
    best <- 0; found <- FALSE
    for (m in 0:15) {
      cands <- if (m == 0L) 0 else c(m * step_yr, -m * step_yr)
      for (cy in cands) {
        ok <- TRUE
        if (length(xl_p) > 0L) {
          x_ovlp <- ci_lo[i] < xr_p & ci_hi[i] > xl_p
          y_close <- abs(cy - cy_p) < step_yr * 0.95
          if (any(x_ovlp & y_close)) ok <- FALSE
        }
        if (ok) { best <- cy; found <- TRUE; break }
      }
      if (found) break
    }
    y[i] <- best
    xl_p <- c(xl_p, ci_lo[i])
    xr_p <- c(xr_p, ci_hi[i])
    cy_p <- c(cy_p, best)
  }
  y
}


# ---- Panel (c): Beeswarm circles ------------------------------------
# Read plot.title style from theme_classic() at runtime so the legend
# title always matches the other panel titles exactly.
pt <- theme_classic()$plot.title
pt_size  <- if (!is.null(pt$size))   pt$size   else rel(1.2)
pt_face  <- if (!is.null(pt$face))   pt$face   else "plain"
pt_color <- if (!is.null(pt$colour)) pt$colour else "black"

# Fixed 5-bin probability scale (0-1 in 20% steps).
# Universal: bin labels and sizes are the same for any record.
# drop = FALSE ensures all 5 bins appear in the legend even if a record
# has no peaks in a given bin.
prob_breaks <- c(0, 0.2, 0.4, 0.6, 0.8, 1.0)
prob_labels <- c("0-20", "21-40", "41-60", "61-80", "81-100")
bin_sizes   <- setNames(c(1.0, 2.5, 4.0, 5.5, 7.5), prob_labels)

# Midpoints used for beeswarm spacing (standardised across records)
bin_mids <- setNames(c(0.10, 0.30, 0.50, 0.70, 0.90), prob_labels)

df_circ <- peak_summaries
df_circ$prob_bin <- cut(df_circ$prob,
                        breaks = prob_breaks,
                        labels = prob_labels,
                        include.lowest = TRUE)
df_circ$prob_mid <- bin_mids[as.character(df_circ$prob_bin)]

df_circ$y_jit <- beeswarm_y(df_circ$ref_age, df_circ$prob_mid,
                             radius_yr = 180, step_yr = 160)

# Ensure every bin level has at least one row so ggplot2 draws a circle in
# the legend key (drop = FALSE keeps the label but not the geom for empty
# levels; NA coordinates are silently ignored by geom_point).
missing_bins <- setdiff(prob_labels, as.character(df_circ$prob_bin))
if (length(missing_bins) > 0L) {
  dummy <- data.frame(
    ref_age    = rep(NA_real_, length(missing_bins)),
    prob       = bin_mids[missing_bins],
    n_detected = NA_integer_,
    mean_age   = NA_real_, median_age = NA_real_, sd_age = NA_real_,
    ci80_lo    = NA_real_, ci80_hi    = NA_real_,
    ci95_lo    = NA_real_, ci95_hi    = NA_real_,
    prob_bin   = factor(missing_bins, levels = prob_labels),
    prob_mid   = bin_mids[missing_bins],
    y_jit      = rep(NA_real_, length(missing_bins))
  )
  df_circ <- rbind(df_circ, dummy)
}

circ_ylim <- range(df_circ$y_jit, na.rm = TRUE) + c(-350, 350)

p_circles <- ggplot(df_circ, aes(x = ref_age, y = y_jit, size = prob_bin)) +
  geom_point(shape = 21L, fill = "grey50", colour = "grey30", alpha = 0.85,
             stroke = 0.5) +
  scale_size_manual(
    values = bin_sizes,
    name   = "(c) P(peak)  (detection frequency, %)",
    drop   = FALSE,
    guide  = guide_legend(
      title.position = "left",
      nrow           = 1,
      override.aes   = list(fill = "grey50", colour = "grey30",
                            alpha = 0.85, stroke = 0.5)
    )
  ) +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = circ_ylim, expand = expansion(0)) +
  theme_classic() +
  theme(axis.title.x  = element_blank(),
        axis.text.x   = element_blank(),
        axis.text.y   = element_blank(),
        axis.ticks.y  = element_blank(),
        axis.line.y   = element_blank(),
        legend.position      = "top",
        legend.justification = "left",
        legend.direction     = "horizontal",
        legend.background    = element_rect(fill = "white", colour = NA),
        legend.title  = element_text(size = pt_size, face = pt_face,
                                     colour = pt_color, vjust = 0.8),
        legend.text   = element_text(size = 9),
        legend.key.size = unit(12, "pt"),
        legend.margin = margin(2, 4, 2, 4)) +
  labs(y = "P(peak)", title = NULL)


# ---- Panel (d): Jittered 95% CI bars ---------------------------------
df_ci <- peak_summaries
df_ci$y_jit <- bar_y(df_ci$ci95_lo, df_ci$ci95_hi, step_yr = 45)

ci_ylim  <- range(df_ci$y_jit) + c(-60, 60)
cap_ht   <- diff(range(df_ci$y_jit)) * 0.08  # end-cap height as fraction of y range

p_ci <- ggplot(df_ci, aes(y = y_jit)) +
  geom_errorbarh(aes(xmin = ci95_lo, xmax = ci95_hi),
                 height = max(cap_ht, 20),
                 colour = "grey30", linewidth = 0.7) +
  geom_point(aes(x = ref_age), shape = 16L, size = 2.0, colour = "grey20") +
  scale_x_reverse(limits = x_lims, breaks = x_ticks,
    minor_breaks = x_minor, labels = x_ticks / 1000,
    expand = expansion(0)) +
  guides(x = guide_axis(minor.ticks = TRUE)) +
  scale_y_continuous(limits = ci_ylim, expand = expansion(0)) +
  theme_classic() +
  theme(axis.text.y  = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y  = element_blank()) +
  labs(x = "cal. yr BP (x 1000)", y = "95% CI",
       title = "(d) 95% CI on peak timing  (1000-chronology ensemble)")


# ---- Assemble --------------------------------------------------------
fig <- pa / p_sni / p_circles / p_ci +
  plot_layout(heights = c(3, 1, 1.2, 1))

print(fig)


# ---- Save ------------------------------------------------------------
out_pdf <- "CharAnalysis_2_0_R/tests/CH10_ensemble_figure.pdf"
ggsave(out_pdf, plot = fig, width = 7, height = 10, units = "in")
message(sprintf("Saved: %s", out_pdf))
